site_name: Feature Generation Benchmark

nav:
  - "Home": "index.md"
  - "Results": "benchmark_results.md"
  - "Development Guide": "dev_guide.md"
  - "GitHub": "https://github.com/SemyonSinchenko/feature-generation-benchmark"

theme:
  name: mkdocs
  highlightjs: true
  hljs_languages:
    - python
    - rust
  color_mode: auto
  user_color_mode_toggle: true
  nav_style: dark
  locale: en
